# yamllint disable rule:line-length

TCEpage:
  author: 'CSBPx'
  author_email: info@csbp.ch
  author_phone: '+41793301011'
  org_name: 'Club Suisse du Berger des Pyrénées'
  org_logo: 'EXT:cpdevsite/Resources/Public/Images/logo-berger.png'

