name: conpassione/stafflist
typeName: stafflist
group: z-cpextensions
prefixFields: false
fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: members
    type: Select
    renderType: selectSingle
    minitems: 0
    maxitems: 1
    foreign_table: pages
    #foreign_table_where: 'AND pages.module="staff" AND ({#pages}.{#sys_language_uid} = ###REC_FIELD_sys_language_uid###) ORDER BY pages.title'
    foreign_table_where: 'AND pages.module="staff" AND ({#pages}.{#sys_language_uid} = 0) ORDER BY pages.title'
  - identifier: cp_status
    type: Radio
    label: "Display"
    defaultValue: 0
    items:
      - label: 'show all'
        value: 0
      - label: 'hide Address'
        value: 1
      - label: 'hide Fon'
        value: 2
      - label: 'hide Address and Fon'
        value: 3
      - label: 'hide eMail'
        value: 4
      - label: 'hide Address and eMail'
        value: 5
      - label: 'hide Fon and eMail'
        value: 6
      - label: 'hide Address, Fon and eMail'
        value: 7
basics:
  - TYPO3/Appearance
  - TYPO3/Links
