enforce:
  #includeResolutions: false
  inheritDefault: true
  mutations:
    - mode: "extend"
      directive: "default-src"
      sources:
        - "'self'"

    - mode: "extend"
      directive: "script-src"
      sources:
        - "'unsafe-eval'"
report:
  #includeResolutions: false
  inheritDefault: true
  mutations:
    - mode: "extend"
      directive: "default-src"
      sources:
        - "'self'"

    - mode: "extend"
      directive: "script-src"
      sources:
        - "'nonce-*'"
