name: conpassione/member
typeName: conpassione-member
title: 'Mitglied'
group: conpassione
table: tx_conpassione_member
lableField: title
sortField: title
security:
  ignorePageTypeRestriction: true

fields:
- identifier: title
  type: 'Text'
  label: 'Funktion'
- identifier: feuser
  type: 'Select'
  renderType: selectSingle
  foreign_table: fe_users
  label: 'FE-User'
  labelField: name
- identifier: board
  label: 'Board'
  type: Select
  renderType: selectSingle
  items:
    - value: 1
    - value: 2

