# CKE-Editor CpBase-Configuration
# Load default processing options
imports:
  - { resource: './Editor/Processing.yaml' }
  - { resource: './Editor/Base.yaml' }
  - { resource: './Editor/Plugins.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
  config:
    style:
      definitions:
        # block level styles
        - { name: 'Orange title H3', element: 'h3', classes: ['h3class abc'], styles: { color: '#ff3300', background: 'blue' } }
        - { name: 'Quote / Citation', element: 'blockquote', classes: [],  }
        - { name: 'Code block', element: 'p', classes: ['codeblockclass'],  }
        # Inline styles
        - { name: 'Yellow marker', element: 'span', classes: ['cp-yellow'], styles: { background-color: 'yellow' } }

    heading:
      options:
        - { model: 'paragraph', title: 'Absatz' }
        - { model: 'heading3', view: 'h3', title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:tceform.header_layout.Label3' }
        - {
          model: 'headingfancy',
          view: {
            name: 'h3',
            classes: 'fancy'
          },
          title: 'H-fancy',
          converterPriority: 'high'
        }
        - { model: 'heading4', view: 'h4', title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:tceform.header_layout.Label4' }
        #- { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }

    toolbar:
      items:
        - clipboard
        - removeFormat
        - undo
        - redo
        - '|'
        - findAndReplace
        - selectAll
        - '|'
        - link
        - '|'
        - bold
        - italic
        - underline
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - indent
        - outdent
        - alignment
        - '|'
        - specialCharacters
        - '-'
        - style
        - heading
        - '|'
        - sourceEditing
        - showBlocks
        - '|'
        - pasteFromOffice
        - codeBlock
        # - { label: 'Table', icon: 'threeVerticalDots', items: [ 'insertTable', 'tableColumn', 'tableRow', 'mergeTableCells' ] }
        # - insertTable
        # - tableColumn
        # - tableRow
        # - mergeTableCells
        # - horizontalLine
        # line break
#        - strikethrough
#        - subscript
#        - superscript
#        - table
        # - '-'
        # - fontFamily
        # - fontBackgroundColor
        # - fontColor
        # - fontSize

    alignment:
      options:
        - { name: 'left', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }

    table:
      defaultHeadings: { rows: 1, columns: 1 }
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties
        - toggleTableCaption

    codeBlock:
      languages: [
        { language: 'plaintext', label: 'Text', class: '' },
        { language: 'bash', label: 'Bash' },
        { language: 'html', label: 'HTML' },
        { language: 'css', label: 'CSS' },
        { language: 'php', label: 'PHP' },
        { language: 'typoscript', lable: 'TypoScript'}
      ]

#    pasteFromOffice:
#      isEnabled: 'true'

#    fontColor:
#      colors:
#        - { label: 'Orange', color: '#ff8700' }
#        - { label: 'Blue', color: '#0080c9' }
#        - { label: 'Green', color: '#209d44' }

#    fontBackgroundColor:
#      colors:
#        - { label: 'Stage orange light', color: '#fab85c' }

#    fontFamily:
#      options:
#        - 'default'
#        - 'Arial, sans-serif'

#    fontSize:
#      options:
#        - 'default'
#        - 18
#        - 22

    plugins:
      - PasteFromOffice

    importModules:
      #- { 'module': '@ckeditor/ckeditor5-font', 'exports': ['Font'] }
      - { module: '@ckeditor/ckeditor5-show-blocks', exports: ['ShowBlocks'] }
      - { module: '@ckeditor/ckeditor5-word-count', exports: ['WordCount'] }
      - { module: '@ckeditor/ckeditor5-code-block', exports: ['CodeBlock'] }
      - { module: '@ckeditor/ckeditor5-find-and-replace', exports: ['FindAndReplace'] }
      - { module: '@ckeditor/ckeditor5-paste-from-office', exports: ['PasteFromOffice'] }
