# CKE-Editor CpBase-Configuration
# Load default processing options
imports:
  - { resource: './Editor/Processing.yaml' }
  - { resource: './Editor/Base.yaml' }
  - { resource: './Editor/Plugins.yaml' }
  - { resource: './Buttons.yaml' }
#  - { resource: './CodeBlock.yaml' }


# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
  config:
    defaultContentLanguage: "de"
    defaultLanguage: "de"
    contentsLanguage: "de"
    language: "de"
    scayt_autoStartup: true # Spellcheck always on
    scayt_sLang: "de_CH" # spellcheck language
    wsc_lang: "de_CH"

    style:
      definitions:
        # block level styles
        - { name: 'Orange title H3', element: 'h3', classes: ['h3class test'], styles: { color: '#ff3300', background-color: 'blue' } }
        - { name: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.blockstyle.labelquote', element: 'blockquote', classes: [],  }
        - { name: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.blockstyle.labelcodeblock', element: 'p', classes: ['codeblockclass'],  }
        # Inline styles
        - { name: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.inlinestyle.labelsuccess', element: 'span', classes: ['cp-success'], styles: { background-color: 'green' } }
        - { name: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.inlinestyle.labelwarning', element: 'span', classes: ['cp-warning'], styles: { background-color: 'yellow' } }
        - { name: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.inlinestyle.labelerror', element: 'span', classes: ['cp-error'], styles: { background-color: 'red' } }

    heading:
      options:
        - { model: 'paragraph', view: 'p', title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.heading.labelparagraph' }
        - { model: 'heading3', view: 'h3', title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:tceform.header_layout.labelh3' }
        - { model: 'heading4', view: 'h4', title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:tceform.header_layout.labelh4' }
         #- { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }
#        - {
#          model: 'headingfancy',
#          view: {
#            name: 'h3',
#            classes: 'fancy'
#          },
#          title: 'H-fancy',
#          converterPriority: 'high'
#        }

    toolbar:
      items:
        - clipboard
        - removeFormat
        - undo
        - redo
        - '|'
        - findAndReplace
        - selectAll
        - '|'
        - link
        - '|'
        - bold
        - italic
        - underline
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - indent
        - outdent
        - alignment
        - '|'
        - specialCharacters
        - '-'
        - style
        - heading
        - '|'
        - sourceEditing
        - showBlocks
        - '|'
        - pasteFromOffice
        - { label: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.toolbar.items.table', withText: true, items: [ 'insertTable', 'tableColumn', 'tableRow', 'mergeTableCells' ] }

    alignment:
      options:
        - { name: 'left', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }

    table:
      defaultHeadings: { rows: 1, columns: 1 }
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties
        - toggleTableCaption

    plugins:
      - PasteFromOffice
