# CKE-Editor CpBase-Configuration
# Load default processing options
imports:
  - { resource: 'EXT:rte-ckeditor/Configuration/RTE/Processing.yaml' }
  - { resource: 'EXT:rte-ckeditor/Configuration/RTE/Editor/Base.yaml' }
  - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }
  #- { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/LinkBrowser.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/Base.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/Plugins.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/LinkBrowser.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/CodeBlock.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/Styles.yaml' }
  - { resource: 'EXT:cpdevsite/Configuration/RTE/Editor/Languages.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
  config:
    toolbar:
      items:
        - style
        - heading
        - '|'
        - removeFormat
        - undo
        - redo
        - findAndReplace
        - '|'
        - bold
        - italic
        - underline
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - '|'
        - alignment
        - '|'
        - specialCharacters
        - codeBlock
        - '|'
        - link
        - '|'
        - { label: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:rte.toolbar.items.table', withText: true, items: [ 'insertTable', 'tableColumn', 'tableRow', 'mergeTableCells' ] }
        - '|'
        - showBlocks
        - '|'
        - sourceEditing
        #- pasteFromOffice
        #- textPartLanguage

    alignment:
      options:
        - { name: 'links', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }

    table:
      defaultHeadings: { rows: 1, columns: 1 }
      contentToolbar:
        - tableColumn
        - tableRow
        - mergeTableCells
        - tableProperties
        - tableCellProperties
        - toggleTableCaption
