name: conpassione/cpmember
typeName: cpmember
title: 'Mitglied'
group: conpassione
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
  - identifier: feuser
    type: 'Select'
    label: 'FE-User'
    renderType: selectSingle
    foreign_table: fe_users
    foreign_table_where: 'ORDER BY fe_users.name'
    labelField: name
    minitems: 0
    maxitems: 1
    items:
      - label: vakant
        value: 0
