name: conpassione/submenupage
typeName: 36650011
title: Untermenuseite
group: conpassione
description: Das ist die Uebersichtsseite für Galerien
prefixFields: false
fields:
  - identifier: subtitle
    useExistingField: true


