
renderingOptions:
  submitButtonLabel: Absenden
type: Form
identifier: mitgliedschaft
label: Mitgliedschaft
prototypeName: standard
finishers:
  -
    options:
      subject: 'Beantragung Mitgliedschaft im CSBP'
      recipients:
        info@csbp.ch: 'Club Suisse du Berger des Pyrénées'
      senderAddress: '{email}'
      senderName: '{nachname}  {vorname}'
      addHtmlPart: true
      attachUploads: false
      title: 'Beantragung Mitgliedschaft für den Club Suisse du Berger des Pyrénées für  {vorname} {nachname}'
    identifier: EmailToSender
  -
    options:
      subject: Mitgliedschaftsantrag
      recipients:
        info@csbp.ch: CSBP
      senderAddress: '{email}'
      senderName: '{nachname}  {vorname}'
      addHtmlPart: true
      attachUploads: false
      translation:
        language: Standard
      title: ''
    identifier: EmailToReceiver
  -
    options:
      message: 'Besten Dank für Ihre Anmeldung.'
      contentElementUid: ''
    identifier: Confirmation
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Nächster Schritt'
    type: Page
    identifier: page-1
    label: Hauptmitglied
    renderables:
      -
        properties:
          options:
            Herr: Herr
            Frau: Frau
            anderes: anderes
          elementDescription: 'Bitte Anrede wählen'
        type: SingleSelect
        identifier: selectAnrede
        label: Anrede
        defaultValue: Herr
      -
        defaultValue: ''
        type: Text
        identifier: nachname
        label: Name
        properties:
          elementDescription: 'Name des Mitgliedes'
          fluidAdditionalAttributes:
            required: required
            minlength: '1'
            maxlength: '100'
          validationErrorMessages:
            -
              code: 1238110957
              message: 'Bitte Name erfassen'
            -
              code: 1269883975
              message: 'Bitte Name erfassen'
            -
              code: 1428504122
              message: 'Bitte Name erfassen'
            -
              code: 1238108068
              message: 'Bitte Name erfassen'
            -
              code: 1238108069
              message: 'Bitte Name erfassen'
            -
              code: 1221560910
              message: 'Der Name ist notwendig'
            -
              code: 1221560718
              message: 'Der Name ist notwendig'
            -
              code: 1347992400
              message: 'Der Name ist notwendig'
            -
              code: 1347992453
              message: 'Der Name ist notwendig'
        validators:
          -
            identifier: NotEmpty
          -
            options:
              minimum: '1'
              maximum: '100'
            identifier: StringLength
      -
        defaultValue: ''
        type: Text
        identifier: vorname
        label: Vorname
        properties:
          elementDescription: 'Vorname des Mitgliedes'
          fluidAdditionalAttributes:
            required: required
            minlength: '1'
            maxlength: '100'
          validationErrorMessages:
            -
              code: 1221560910
              message: 'Bitte Vorname ausfüllen'
            -
              code: 1221560718
              message: 'Bitte Vorname ausfüllen'
            -
              code: 1347992400
              message: 'Bitte Vorname ausfüllen'
            -
              code: 1347992453
              message: 'Bitte Vorname ausfüllen'
            -
              code: 1238110957
              message: 'Bitte Vorname erfassen'
            -
              code: 1269883975
              message: 'Bitte Vorname erfassen'
            -
              code: 1428504122
              message: 'Bitte Vorname erfassen'
            -
              code: 1238108068
              message: 'Bitte Vorname erfassen'
            -
              code: 1238108069
              message: 'Bitte Vorname erfassen'
        validators:
          -
            identifier: NotEmpty
          -
            options:
              minimum: '1'
              maximum: '100'
            identifier: StringLength
      -
        defaultValue: ''
        type: Textarea
        identifier: adresse
        label: Adresse
        properties:
          elementDescription: Strassenanschrift
      -
        defaultValue: ''
        type: Text
        identifier: plzOrt
        label: 'PLZ Ort'
        properties:
          elementDescription: 'Postleitzahl und Ort'
      -
        defaultValue: ''
        type: Text
        identifier: telefon
        label: Telefon
        properties:
          elementDescription: ''
      -
        defaultValue: ''
        type: Text
        identifier: mobile
        label: Mobile
        properties:
          elementDescription: ''
          fluidAdditionalAttributes:
            required: required
            minlength: '10'
            maxlength: '25'
          validationErrorMessages:
            -
              code: 1238110957
              message: 'Vollständige Telefonnummer erfassen'
            -
              code: 1269883975
              message: 'Vollständige Telefonnummer erfassen'
            -
              code: 1428504122
              message: 'Vollständige Telefonnummer erfassen'
            -
              code: 1238108068
              message: 'Vollständige Telefonnummer erfassen'
            -
              code: 1238108069
              message: 'Vollständige Telefonnummer erfassen'
            -
              code: 1221560910
              message: 'Bitte Mobile-Nummer erfassen'
            -
              code: 1221560718
              message: 'Bitte Mobile-Nummer erfassen'
            -
              code: 1347992400
              message: 'Bitte Mobile-Nummer erfassen'
            -
              code: 1347992453
              message: 'Bitte Mobile-Nummer erfassen'
        validators:
          -
            identifier: NotEmpty
          -
            options:
              minimum: '10'
              maximum: '25'
            identifier: StringLength
      -
        defaultValue: ''
        type: Email
        identifier: email
        label: E-Mail
        properties:
          fluidAdditionalAttributes:
            required: required
            autocomplete: email
          validationErrorMessages:
            -
              code: 1221560910
              message: 'Bitte E-Mail Adresse erfassen'
            -
              code: 1221560718
              message: 'Bitte E-Mail Adresse erfassen'
            -
              code: 1347992400
              message: 'Bitte E-Mail Adresse erfassen'
            -
              code: 1347992453
              message: 'Bitte E-Mail Adresse erfassen'
            -
              code: 1221559976
              message: 'Die E-Mail ist für die Kommunikation nötig'
          elementDescription: 'Die E-Mail Adresse wird für die Kommunikation benötigt.'
        validators:
          -
            identifier: EmailAddress
          -
            identifier: NotEmpty
      -
        type: Checkbox
        identifier: datenSchut
        label: 'Ich bin einverstanden, dass die erfassten Daten für die Zwecke des Club verwendet werden.'
        properties:
          elementDescription: ''
          fluidAdditionalAttributes:
            required: required
          validationErrorMessages:
            -
              code: 1221560910
              message: 'Bitte Verwendung der Daten zustimmen'
            -
              code: 1221560718
              message: 'Bitte Verwendung der Daten zustimmen'
            -
              code: 1347992400
              message: 'Bitte Verwendung der Daten zustimmen'
            -
              code: 1347992453
              message: 'Bitte Verwendung der Daten zustimmen'
        validators:
          -
            identifier: NotEmpty
