name: conpassione/homepage1
typeName: 36650001
title: HomePage1
group: landingpage
description: This is the rootpage of theme 1
prefixFields: false
fields:
  - identifier: subtitle
    useExistingField: true
  - identifier: cplogo
    label: Brand Logo
    type: File
    extendedPalette: true
    minitems: 0
    maxitems: 1
    allowed: svg
    cropVariants:
      logocrp:
        title: 'LLL:EXT:cpdevsite/Resources/Private/Language/locallang_db.xlf:tceform.frame_class.labeldefault'
        allowedAspectRatios:
          LogoL:
            title: '2:1'
            value: 2 / 1
          LogoP:
            title: '1:2'
            value: 1 / 2
        selectedRatio: LogoL
